DROP TABLE PERSONAS CASCADE CONSTRAINS;
CREATE TABLE PERSONAS(
    ID_PERSONA          INTEGER AUTO_INCREMENT,   
    NOMBRE              VARCHAR(50) NOT NULL,
    PRIMER_APELLIDO     VARCHAR(50) NOT NULL,
    SEGUNDO_APELLIDO    VARCHAR(50),
    DNI                 VARCHAR(9) NOT NULL,
    MOVIL               VARCHAR(9) NOT NULL,
    FECHA_NACIMIENTO    DATE NOT NULL,        
    CONSTRAINT PK_PERSONAS PRIMARY KEY (ID_USUARIO),
);

DROP TABLE ENTRENADORES CASCADE CONSTRAINS;
CREATE TABLE ENTRENADORES(
    ID_ENTRENADOR   INTEGER AUTO_INCREMENT,
    CORREO          VARCHAR(50) NOT NULL,
    CONSTRASEÑA     VARCHAR(50) NOT NULL, /*ENCRIPTAR AL INSERTAR SHA1*/
    ID_PERSONA      INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_PERSONAS_ENTRENADORES FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID_PERSONA)
);

DROP TABLE ALUMNOS CASCADE CONSTRAINS;
CREATE TABLE ALUMNOS(
    ID_ALUMNO   INTEGER AUTO_INCREMENT,
    PESO        INTEGER,
    ALTURA      INTEGER,
    MANO_DOM    VARCHAR(20),
	PIE_DOM		VARCHAR(20),
	OBSERVACIONES VARCHAR(100),
	ID_PERSONA      INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_ALUMNOS PRIMARY KEY (ID_ALUMNO),
    CONSTRAINT FK_PERSONAS_ALUMNOS FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID_PERSONA)
);

DROP TABLE GRUPOS CASCADE CONSTRAINS;
CREATE TABLE GRUPOS(
    ID_GRUPO        INTEGER AUTO_INCREMENT,
    NOMBRE          VARCHAR(20) NOT NULL,
    ID_RESPONSABLE  INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_GRUPO PRIMARY KEY (ID_GRUPO),
    CONSTRAINT FK_ENTRENADOR_GRUPOS (ID_RESPONSABLE) REFERENCES ENTRENADORES (ID_ENTRENADOR)
);

DROP TABLE GRUPOS_ALUMNOS CASCADE CONSTRAINS;
CREATE TABLE GRUPOS_ALUMNOS (
    ID_GRUPO    INTEGER AUTO_INCREMENT,    
    ID_ALUMNO  	INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_GRUP_ALUMN PRIMARY KEY (ID_GRUPO, ID_ALUMNO),
    CONSTRAINT FK_GRUPALUM_GRUPOS (ID_GRUPO) REFERENCES GRUPOS (ID_GRUPO),
	CONSTRAINT FK_GRUPALUM_ALUMN (ID_ALUMNO) REFERENCES ALUMNOS (ID_ALUMNO)
);

DROP TABLE DEPORTES CASCADE CONSTRAINS;
CREATE TABLE DEPORTES(
    ID_DEPORTE      INTEGER AUTO_INCREMENT,
    NOMBRE          VARCHAR(20) NOT NULL,
);

DROP TABLE EJERCICIOS CASCADE CONSTRAINS;
CREATE TABLE EJERCICIOS(
    ID_EJERCICIO       INTEGER AUTO_INCREMENT,
    NOMBRE             VARCHAR(20) NOT NULL,
    DESCRIPCION        VARCHAR(50),
    ID_DEPORTE         INTEGER AUTO_INCREMENT,
    ID_ENTRENADOR      INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_EJERCICIOS PRIMARY KEY (ID_EJERCICIO),
    CONSTRAINT FK_ENTRENADOR_EJERCICIOS FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADORES (ID_ENTRENADOR),
    CONSTRAINT FK_DEPORTES FOREIGN KEY (ID_DEPORTE) REFERENCES DEPORTES (ID_DEPORTE)
);

DROP TABLE ENTRENAMIENTOS CASCADE CONSTRAINS;
CREATE TABLE ENTRENAMIENTOS(
    ID_ENTRENAMIENTO        INTEGER AUTO_INCREMENT,
    REALIZADO               BOOLEAN NOT NULL,
    MOTIVO_CANCEL           VARCHAR(100),
    FECHA                   DATE,
    ID_ENTRENADOR           INTEGER AUTO_INCREMENT,
    ID_GRUPO                INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_ENTRENAMIENTO PRIMARY KEY (ID_ENTRENADOR),
    CONSTRAINT FK_PERSONAS_ENTRENAMIENTO FOREIGN KEY (ID_ENTRENADOR) REFERENCES PERSONAS (ID_PERSONA),
    CONSTRAINT FK_GRUPO_ENTRENAMIENTO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID_GRUPO),
);



/*FALTA CREAR LAS TABLAS DE LAS RELACIONES MUCHOS A MUCHOS, GRUPOSDEPORTES, GRUPOSPERSONAS, EJERCICIOSENTRENAMIENTO*/


/*


TABLA_HORARIOS
hora_clase
Id_profesor FK(references table Personas)
Id_grupo FK( references table Grupos)
Dueacion_clase ( lo haría tipo flooat y luego calcularía cuántas horas son, ex 1,50 == 1h 30min)
*/

