DROP TABLE TIPOS_USUARIOS CASCADE CONSTRAINS;
CREATE TABLE TIPOS_USUARIOS(
    ID_TIPOS_USUARIOS       VARCHAR(5) NOT NULL,
    NOMBRE                  VARCHAR(20),
    CONSTRAINT PK_TIPOS_USUARIOS PRIMARY KEY (ID_TIPOS_USUARIOS)
);

DROP TABLE PERSONAS CASCADE CONSTRAINS;
CREATE TABLE PERSONAS(
    ID_PERSONA          INTEGER AUTO_INCREMENT,   
    NOMBRE              VARCHAR(50) NOT NULL,
    PRIMER_APELLIDO     VARCHAR(50) NOT NULL,
    SEGUNDO_APELLIDO    VARCHAR(50),
    DNI                 VARCHAR(9) NOT NULL,
    MOVIL               VARCHAR(9) NOT NULL,
    FECHA_NACIMIENTO    DATE NOT NULL,
    ID_TIPOS_USUARIO    VARCHAR(5) NOT NULL,
    ID_GRUPO            INTEGER AUTO_INCREMENT,
    ID_EJERCICIO        INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_PERSONAS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_TIPOS_USUARIOS FOREIGN KEY (ID_TIPOS_USUARIO) REFERENCES TIPOS_USUARIOS (ID_TIPOS_USUARIOS),
    CONSTRAINT FK_GRUPOS FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID_GRUPO),
    CONSTRAINT FK_EJERCICIOS FOREIGN KEY (ID_EJERCICIO) REFERENCES EJERCICIOS (ID_EJERCICIO) 
);


DROP TABLE USUARIOS CASCADE CONSTRAINS;
CREATE TABLE USUARIOS(
    ID_USUARIO      INTEGER AUTO_INCREMENT,
    CORREO          VARCHAR(50) NOT NULL,
    CONSTRASEÑA     VARCHAR(50) NOT NULL, /*ENCRIPTAR AL INSERTAR SHA1*/
    ID_PERSONA      INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_PERSONAS_USUARIOS FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID_PERSONA)
    
);

DROP TABLE GRUPOS CASCADE CONSTRAINS;
CREATE TABLE GRUPOS(
    ID_GRUPO        INTEGER AUTO_INCREMENT,
    NOMBRE          VARCHAR(20) NOT NULL,
    ID_RESPONSABLE  INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_GRUPO PRIMARY KEY (ID_GRUPO),
    CONSTRAINT FK_PERSONAS_GRUPOS (ID_RESPONSABLE) REFERENCES PERSONAS (ID_PERSONA)
);

DROP TABLE DEPORTES CSACADE CONSTRAINS;
CREATE TABLE DEPORTES(
    ID_DEPORTE      INTEGER AUTO_INCREMENT,
    NOMBRE          VARCHAR(20) NOT NULL,
);

DROP TABLE EJERCICIOS CASCADE CONSTRAINS;
CREATE TABLE EJERCICIOS(
    ID_EJERCICIO       INTEGER AUTO_INCREMENT,
    NOMBRE             VARCHAR(20) NOT NULL,
    DESCRIPCION        VARCHAR(50),
    ID_DEPORTE         INTEGER AUTO_INCREMENT,
    ID_PERSONA         INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_EJERCICIOS PRIMARY KEY (ID_EJERCICIO),
    CONSTRAINT FK_PERSONAS_EJERCICIOS FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS (ID_PERSONA),
    CONSTRAINT FK_DEPORTES FOREIGN KEY (ID_DEPORTE) REFERENCES DEPORTES (ID_DEPORTE)
);


DROP TABLE ENTRENAMIENTOS CASCADE CONSTRAINS;
CREATE TABLE ENTRENAMIENTOS(
    ID_ENTRENAMIENTO        INTEGER AUTO_INCREMENT,
    REALIZADO               BOOLEAN NOT NULL,
    MOTIVO_CANCEL           VARCHAR(100),
    FECHA                   DATE,
    ID_ENTRENADOR           INTEGER AUTO_INCREMENT,
    ID_GRUPO                INTEGER AUTO_INCREMENT,
    CONSTRAINT PK_ENTRENAMIENTO PRIMARY KEY (ID_ENTRENADOR),
    CONSTRAINT FK_PERSONAS_ENTRENAMIENTO FOREIGN KEY (ID_ENTRENADOR) REFERENCES PERSONAS (ID_PERSONA),
    CONSTRAINT FK_GRUPO_ENTRENAMIENTO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID_GRUPO),
);


/*FALTA CREAR LAS TABLAS DE LAS RELACIONES MUCHOS A MUCHOS, GRUPOSDEPORTES, GRUPOSPERSONAS, EJERCICIOSENTRENAMIENTO*/


/*


TABLA_HORARIOS
hora_clase
Id_profesor FK(references table Personas)
Id_grupo FK( references table Grupos)
Dueacion_clase ( lo haría tipo flooat y luego calcularía cuántas horas son, ex 1,50 == 1h 30min)
*/

